// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// AuditAuthMock is a mock implementation of server.AuditAuth.
//
//	func TestSomethingThatUsesAuditAuth(t *testing.T) {
//
//		// make and configure a mocked server.AuditAuth
//		mockedAuditAuth := &AuditAuthMock{
//			GetSessionUserFunc: func(ctx context.Context, token string) (string, bool) {
//				panic("mock out the GetSessionUser method")
//			},
//			HasTokenACLFunc: func(token string) bool {
//				panic("mock out the HasTokenACL method")
//			},
//			IsAdminFunc: func(username string) bool {
//				panic("mock out the IsAdmin method")
//			},
//		}
//
//		// use mockedAuditAuth in code that requires server.AuditAuth
//		// and then make assertions.
//
//	}
type AuditAuthMock struct {
	// GetSessionUserFunc mocks the GetSessionUser method.
	GetSessionUserFunc func(ctx context.Context, token string) (string, bool)

	// HasTokenACLFunc mocks the HasTokenACL method.
	HasTokenACLFunc func(token string) bool

	// IsAdminFunc mocks the IsAdmin method.
	IsAdminFunc func(username string) bool

	// calls tracks calls to the methods.
	calls struct {
		// GetSessionUser holds details about calls to the GetSessionUser method.
		GetSessionUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// HasTokenACL holds details about calls to the HasTokenACL method.
		HasTokenACL []struct {
			// Token is the token argument value.
			Token string
		}
		// IsAdmin holds details about calls to the IsAdmin method.
		IsAdmin []struct {
			// Username is the username argument value.
			Username string
		}
	}
	lockGetSessionUser sync.RWMutex
	lockHasTokenACL    sync.RWMutex
	lockIsAdmin        sync.RWMutex
}

// GetSessionUser calls GetSessionUserFunc.
func (mock *AuditAuthMock) GetSessionUser(ctx context.Context, token string) (string, bool) {
	if mock.GetSessionUserFunc == nil {
		panic("AuditAuthMock.GetSessionUserFunc: method is nil but AuditAuth.GetSessionUser was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGetSessionUser.Lock()
	mock.calls.GetSessionUser = append(mock.calls.GetSessionUser, callInfo)
	mock.lockGetSessionUser.Unlock()
	return mock.GetSessionUserFunc(ctx, token)
}

// GetSessionUserCalls gets all the calls that were made to GetSessionUser.
// Check the length with:
//
//	len(mockedAuditAuth.GetSessionUserCalls())
func (mock *AuditAuthMock) GetSessionUserCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGetSessionUser.RLock()
	calls = mock.calls.GetSessionUser
	mock.lockGetSessionUser.RUnlock()
	return calls
}

// HasTokenACL calls HasTokenACLFunc.
func (mock *AuditAuthMock) HasTokenACL(token string) bool {
	if mock.HasTokenACLFunc == nil {
		panic("AuditAuthMock.HasTokenACLFunc: method is nil but AuditAuth.HasTokenACL was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockHasTokenACL.Lock()
	mock.calls.HasTokenACL = append(mock.calls.HasTokenACL, callInfo)
	mock.lockHasTokenACL.Unlock()
	return mock.HasTokenACLFunc(token)
}

// HasTokenACLCalls gets all the calls that were made to HasTokenACL.
// Check the length with:
//
//	len(mockedAuditAuth.HasTokenACLCalls())
func (mock *AuditAuthMock) HasTokenACLCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockHasTokenACL.RLock()
	calls = mock.calls.HasTokenACL
	mock.lockHasTokenACL.RUnlock()
	return calls
}

// IsAdmin calls IsAdminFunc.
func (mock *AuditAuthMock) IsAdmin(username string) bool {
	if mock.IsAdminFunc == nil {
		panic("AuditAuthMock.IsAdminFunc: method is nil but AuditAuth.IsAdmin was just called")
	}
	callInfo := struct {
		Username string
	}{
		Username: username,
	}
	mock.lockIsAdmin.Lock()
	mock.calls.IsAdmin = append(mock.calls.IsAdmin, callInfo)
	mock.lockIsAdmin.Unlock()
	return mock.IsAdminFunc(username)
}

// IsAdminCalls gets all the calls that were made to IsAdmin.
// Check the length with:
//
//	len(mockedAuditAuth.IsAdminCalls())
func (mock *AuditAuthMock) IsAdminCalls() []struct {
	Username string
} {
	var calls []struct {
		Username string
	}
	mock.lockIsAdmin.RLock()
	calls = mock.calls.IsAdmin
	mock.lockIsAdmin.RUnlock()
	return calls
}
