// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/git"
)

// GitStoreMock is a mock implementation of server.GitStore.
//
//	func TestSomethingThatUsesGitStore(t *testing.T) {
//
//		// make and configure a mocked server.GitStore
//		mockedGitStore := &GitStoreMock{
//			CommitFunc: func(req git.CommitRequest) error {
//				panic("mock out the Commit method")
//			},
//			DeleteFunc: func(key string, author git.Author) error {
//				panic("mock out the Delete method")
//			},
//			PullFunc: func() error {
//				panic("mock out the Pull method")
//			},
//			PushFunc: func() error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedGitStore in code that requires server.GitStore
//		// and then make assertions.
//
//	}
type GitStoreMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func(req git.CommitRequest) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(key string, author git.Author) error

	// PullFunc mocks the Pull method.
	PullFunc func() error

	// PushFunc mocks the Push method.
	PushFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Req is the req argument value.
			Req git.CommitRequest
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Key is the key argument value.
			Key string
			// Author is the author argument value.
			Author git.Author
		}
		// Pull holds details about calls to the Pull method.
		Pull []struct {
		}
		// Push holds details about calls to the Push method.
		Push []struct {
		}
	}
	lockCommit sync.RWMutex
	lockDelete sync.RWMutex
	lockPull   sync.RWMutex
	lockPush   sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *GitStoreMock) Commit(req git.CommitRequest) error {
	if mock.CommitFunc == nil {
		panic("GitStoreMock.CommitFunc: method is nil but GitStore.Commit was just called")
	}
	callInfo := struct {
		Req git.CommitRequest
	}{
		Req: req,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(req)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedGitStore.CommitCalls())
func (mock *GitStoreMock) CommitCalls() []struct {
	Req git.CommitRequest
} {
	var calls []struct {
		Req git.CommitRequest
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *GitStoreMock) Delete(key string, author git.Author) error {
	if mock.DeleteFunc == nil {
		panic("GitStoreMock.DeleteFunc: method is nil but GitStore.Delete was just called")
	}
	callInfo := struct {
		Key    string
		Author git.Author
	}{
		Key:    key,
		Author: author,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(key, author)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedGitStore.DeleteCalls())
func (mock *GitStoreMock) DeleteCalls() []struct {
	Key    string
	Author git.Author
} {
	var calls []struct {
		Key    string
		Author git.Author
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Pull calls PullFunc.
func (mock *GitStoreMock) Pull() error {
	if mock.PullFunc == nil {
		panic("GitStoreMock.PullFunc: method is nil but GitStore.Pull was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPull.Lock()
	mock.calls.Pull = append(mock.calls.Pull, callInfo)
	mock.lockPull.Unlock()
	return mock.PullFunc()
}

// PullCalls gets all the calls that were made to Pull.
// Check the length with:
//
//	len(mockedGitStore.PullCalls())
func (mock *GitStoreMock) PullCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPull.RLock()
	calls = mock.calls.Pull
	mock.lockPull.RUnlock()
	return calls
}

// Push calls PushFunc.
func (mock *GitStoreMock) Push() error {
	if mock.PushFunc == nil {
		panic("GitStoreMock.PushFunc: method is nil but GitStore.Push was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc()
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedGitStore.PushCalls())
func (mock *GitStoreMock) PushCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
