// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/store"
)

// ServiceStoreMock is a mock implementation of server.ServiceStore.
//
//	func TestSomethingThatUsesServiceStore(t *testing.T) {
//
//		// make and configure a mocked server.ServiceStore
//		mockedServiceStore := &ServiceStoreMock{
//			DeregisterServiceFunc: func(name string, id string) error {
//				panic("mock out the DeregisterService method")
//			},
//			GetServicesFunc: func(name string, healthyOnly bool) ([]store.ServiceInstance, error) {
//				panic("mock out the GetServices method")
//			},
//			GetServicesForHealthCheckFunc: func(checkType store.HealthCheckType) ([]store.ServiceInstance, error) {
//				panic("mock out the GetServicesForHealthCheck method")
//			},
//			ListServicesSummaryFunc: func() ([]store.ServiceSummary, error) {
//				panic("mock out the ListServicesSummary method")
//			},
//			RegisterServiceFunc: func(svc store.ServiceInstance) error {
//				panic("mock out the RegisterService method")
//			},
//			SetServiceHealthStatusFunc: func(name string, id string, healthy bool) error {
//				panic("mock out the SetServiceHealthStatus method")
//			},
//			UpdateServiceHealthFunc: func(name string, id string) error {
//				panic("mock out the UpdateServiceHealth method")
//			},
//		}
//
//		// use mockedServiceStore in code that requires server.ServiceStore
//		// and then make assertions.
//
//	}
type ServiceStoreMock struct {
	// DeregisterServiceFunc mocks the DeregisterService method.
	DeregisterServiceFunc func(name string, id string) error

	// GetServicesFunc mocks the GetServices method.
	GetServicesFunc func(name string, healthyOnly bool) ([]store.ServiceInstance, error)

	// GetServicesForHealthCheckFunc mocks the GetServicesForHealthCheck method.
	GetServicesForHealthCheckFunc func(checkType store.HealthCheckType) ([]store.ServiceInstance, error)

	// ListServicesSummaryFunc mocks the ListServicesSummary method.
	ListServicesSummaryFunc func() ([]store.ServiceSummary, error)

	// RegisterServiceFunc mocks the RegisterService method.
	RegisterServiceFunc func(svc store.ServiceInstance) error

	// SetServiceHealthStatusFunc mocks the SetServiceHealthStatus method.
	SetServiceHealthStatusFunc func(name string, id string, healthy bool) error

	// UpdateServiceHealthFunc mocks the UpdateServiceHealth method.
	UpdateServiceHealthFunc func(name string, id string) error

	// calls tracks calls to the methods.
	calls struct {
		// DeregisterService holds details about calls to the DeregisterService method.
		DeregisterService []struct {
			// Name is the name argument value.
			Name string
			// ID is the id argument value.
			ID string
		}
		// GetServices holds details about calls to the GetServices method.
		GetServices []struct {
			// Name is the name argument value.
			Name string
			// HealthyOnly is the healthyOnly argument value.
			HealthyOnly bool
		}
		// GetServicesForHealthCheck holds details about calls to the GetServicesForHealthCheck method.
		GetServicesForHealthCheck []struct {
			// CheckType is the checkType argument value.
			CheckType store.HealthCheckType
		}
		// ListServicesSummary holds details about calls to the ListServicesSummary method.
		ListServicesSummary []struct {
		}
		// RegisterService holds details about calls to the RegisterService method.
		RegisterService []struct {
			// Svc is the svc argument value.
			Svc store.ServiceInstance
		}
		// SetServiceHealthStatus holds details about calls to the SetServiceHealthStatus method.
		SetServiceHealthStatus []struct {
			// Name is the name argument value.
			Name string
			// ID is the id argument value.
			ID string
			// Healthy is the healthy argument value.
			Healthy bool
		}
		// UpdateServiceHealth holds details about calls to the UpdateServiceHealth method.
		UpdateServiceHealth []struct {
			// Name is the name argument value.
			Name string
			// ID is the id argument value.
			ID string
		}
	}
	lockDeregisterService         sync.RWMutex
	lockGetServices               sync.RWMutex
	lockGetServicesForHealthCheck sync.RWMutex
	lockListServicesSummary       sync.RWMutex
	lockRegisterService           sync.RWMutex
	lockSetServiceHealthStatus    sync.RWMutex
	lockUpdateServiceHealth       sync.RWMutex
}

// DeregisterService calls DeregisterServiceFunc.
func (mock *ServiceStoreMock) DeregisterService(name string, id string) error {
	if mock.DeregisterServiceFunc == nil {
		panic("ServiceStoreMock.DeregisterServiceFunc: method is nil but ServiceStore.DeregisterService was just called")
	}
	callInfo := struct {
		Name string
		ID   string
	}{
		Name: name,
		ID:   id,
	}
	mock.lockDeregisterService.Lock()
	mock.calls.DeregisterService = append(mock.calls.DeregisterService, callInfo)
	mock.lockDeregisterService.Unlock()
	return mock.DeregisterServiceFunc(name, id)
}

// DeregisterServiceCalls gets all the calls that were made to DeregisterService.
// Check the length with:
//
//	len(mockedServiceStore.DeregisterServiceCalls())
func (mock *ServiceStoreMock) DeregisterServiceCalls() []struct {
	Name string
	ID   string
} {
	var calls []struct {
		Name string
		ID   string
	}
	mock.lockDeregisterService.RLock()
	calls = mock.calls.DeregisterService
	mock.lockDeregisterService.RUnlock()
	return calls
}

// GetServices calls GetServicesFunc.
func (mock *ServiceStoreMock) GetServices(name string, healthyOnly bool) ([]store.ServiceInstance, error) {
	if mock.GetServicesFunc == nil {
		panic("ServiceStoreMock.GetServicesFunc: method is nil but ServiceStore.GetServices was just called")
	}
	callInfo := struct {
		Name        string
		HealthyOnly bool
	}{
		Name:        name,
		HealthyOnly: healthyOnly,
	}
	mock.lockGetServices.Lock()
	mock.calls.GetServices = append(mock.calls.GetServices, callInfo)
	mock.lockGetServices.Unlock()
	return mock.GetServicesFunc(name, healthyOnly)
}

// GetServicesCalls gets all the calls that were made to GetServices.
// Check the length with:
//
//	len(mockedServiceStore.GetServicesCalls())
func (mock *ServiceStoreMock) GetServicesCalls() []struct {
	Name        string
	HealthyOnly bool
} {
	var calls []struct {
		Name        string
		HealthyOnly bool
	}
	mock.lockGetServices.RLock()
	calls = mock.calls.GetServices
	mock.lockGetServices.RUnlock()
	return calls
}

// GetServicesForHealthCheck calls GetServicesForHealthCheckFunc.
func (mock *ServiceStoreMock) GetServicesForHealthCheck(checkType store.HealthCheckType) ([]store.ServiceInstance, error) {
	if mock.GetServicesForHealthCheckFunc == nil {
		panic("ServiceStoreMock.GetServicesForHealthCheckFunc: method is nil but ServiceStore.GetServicesForHealthCheck was just called")
	}
	callInfo := struct {
		CheckType store.HealthCheckType
	}{
		CheckType: checkType,
	}
	mock.lockGetServicesForHealthCheck.Lock()
	mock.calls.GetServicesForHealthCheck = append(mock.calls.GetServicesForHealthCheck, callInfo)
	mock.lockGetServicesForHealthCheck.Unlock()
	return mock.GetServicesForHealthCheckFunc(checkType)
}

// GetServicesForHealthCheckCalls gets all the calls that were made to GetServicesForHealthCheck.
// Check the length with:
//
//	len(mockedServiceStore.GetServicesForHealthCheckCalls())
func (mock *ServiceStoreMock) GetServicesForHealthCheckCalls() []struct {
	CheckType store.HealthCheckType
} {
	var calls []struct {
		CheckType store.HealthCheckType
	}
	mock.lockGetServicesForHealthCheck.RLock()
	calls = mock.calls.GetServicesForHealthCheck
	mock.lockGetServicesForHealthCheck.RUnlock()
	return calls
}

// ListServicesSummary calls ListServicesSummaryFunc.
func (mock *ServiceStoreMock) ListServicesSummary() ([]store.ServiceSummary, error) {
	if mock.ListServicesSummaryFunc == nil {
		panic("ServiceStoreMock.ListServicesSummaryFunc: method is nil but ServiceStore.ListServicesSummary was just called")
	}
	callInfo := struct {
	}{}
	mock.lockListServicesSummary.Lock()
	mock.calls.ListServicesSummary = append(mock.calls.ListServicesSummary, callInfo)
	mock.lockListServicesSummary.Unlock()
	return mock.ListServicesSummaryFunc()
}

// ListServicesSummaryCalls gets all the calls that were made to ListServicesSummary.
// Check the length with:
//
//	len(mockedServiceStore.ListServicesSummaryCalls())
func (mock *ServiceStoreMock) ListServicesSummaryCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockListServicesSummary.RLock()
	calls = mock.calls.ListServicesSummary
	mock.lockListServicesSummary.RUnlock()
	return calls
}

// RegisterService calls RegisterServiceFunc.
func (mock *ServiceStoreMock) RegisterService(svc store.ServiceInstance) error {
	if mock.RegisterServiceFunc == nil {
		panic("ServiceStoreMock.RegisterServiceFunc: method is nil but ServiceStore.RegisterService was just called")
	}
	callInfo := struct {
		Svc store.ServiceInstance
	}{
		Svc: svc,
	}
	mock.lockRegisterService.Lock()
	mock.calls.RegisterService = append(mock.calls.RegisterService, callInfo)
	mock.lockRegisterService.Unlock()
	return mock.RegisterServiceFunc(svc)
}

// RegisterServiceCalls gets all the calls that were made to RegisterService.
// Check the length with:
//
//	len(mockedServiceStore.RegisterServiceCalls())
func (mock *ServiceStoreMock) RegisterServiceCalls() []struct {
	Svc store.ServiceInstance
} {
	var calls []struct {
		Svc store.ServiceInstance
	}
	mock.lockRegisterService.RLock()
	calls = mock.calls.RegisterService
	mock.lockRegisterService.RUnlock()
	return calls
}

// SetServiceHealthStatus calls SetServiceHealthStatusFunc.
func (mock *ServiceStoreMock) SetServiceHealthStatus(name string, id string, healthy bool) error {
	if mock.SetServiceHealthStatusFunc == nil {
		panic("ServiceStoreMock.SetServiceHealthStatusFunc: method is nil but ServiceStore.SetServiceHealthStatus was just called")
	}
	callInfo := struct {
		Name    string
		ID      string
		Healthy bool
	}{
		Name:    name,
		ID:      id,
		Healthy: healthy,
	}
	mock.lockSetServiceHealthStatus.Lock()
	mock.calls.SetServiceHealthStatus = append(mock.calls.SetServiceHealthStatus, callInfo)
	mock.lockSetServiceHealthStatus.Unlock()
	return mock.SetServiceHealthStatusFunc(name, id, healthy)
}

// SetServiceHealthStatusCalls gets all the calls that were made to SetServiceHealthStatus.
// Check the length with:
//
//	len(mockedServiceStore.SetServiceHealthStatusCalls())
func (mock *ServiceStoreMock) SetServiceHealthStatusCalls() []struct {
	Name    string
	ID      string
	Healthy bool
} {
	var calls []struct {
		Name    string
		ID      string
		Healthy bool
	}
	mock.lockSetServiceHealthStatus.RLock()
	calls = mock.calls.SetServiceHealthStatus
	mock.lockSetServiceHealthStatus.RUnlock()
	return calls
}

// UpdateServiceHealth calls UpdateServiceHealthFunc.
func (mock *ServiceStoreMock) UpdateServiceHealth(name string, id string) error {
	if mock.UpdateServiceHealthFunc == nil {
		panic("ServiceStoreMock.UpdateServiceHealthFunc: method is nil but ServiceStore.UpdateServiceHealth was just called")
	}
	callInfo := struct {
		Name string
		ID   string
	}{
		Name: name,
		ID:   id,
	}
	mock.lockUpdateServiceHealth.Lock()
	mock.calls.UpdateServiceHealth = append(mock.calls.UpdateServiceHealth, callInfo)
	mock.lockUpdateServiceHealth.Unlock()
	return mock.UpdateServiceHealthFunc(name, id)
}

// UpdateServiceHealthCalls gets all the calls that were made to UpdateServiceHealth.
// Check the length with:
//
//	len(mockedServiceStore.UpdateServiceHealthCalls())
func (mock *ServiceStoreMock) UpdateServiceHealthCalls() []struct {
	Name string
	ID   string
} {
	var calls []struct {
		Name string
		ID   string
	}
	mock.lockUpdateServiceHealth.RLock()
	calls = mock.calls.UpdateServiceHealth
	mock.lockUpdateServiceHealth.RUnlock()
	return calls
}
