// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"
)

// SessionStoreMock is a mock implementation of server.SessionStore.
//
//	func TestSomethingThatUsesSessionStore(t *testing.T) {
//
//		// make and configure a mocked server.SessionStore
//		mockedSessionStore := &SessionStoreMock{
//			CreateSessionFunc: func(ctx context.Context, token string, username string, expiresAt time.Time) error {
//				panic("mock out the CreateSession method")
//			},
//			DeleteAllSessionsFunc: func(ctx context.Context) error {
//				panic("mock out the DeleteAllSessions method")
//			},
//			DeleteExpiredSessionsFunc: func(ctx context.Context) (int64, error) {
//				panic("mock out the DeleteExpiredSessions method")
//			},
//			DeleteSessionFunc: func(ctx context.Context, token string) error {
//				panic("mock out the DeleteSession method")
//			},
//			DeleteSessionsByUsernameFunc: func(ctx context.Context, username string) error {
//				panic("mock out the DeleteSessionsByUsername method")
//			},
//			GetSessionFunc: func(ctx context.Context, token string) (string, time.Time, error) {
//				panic("mock out the GetSession method")
//			},
//		}
//
//		// use mockedSessionStore in code that requires server.SessionStore
//		// and then make assertions.
//
//	}
type SessionStoreMock struct {
	// CreateSessionFunc mocks the CreateSession method.
	CreateSessionFunc func(ctx context.Context, token string, username string, expiresAt time.Time) error

	// DeleteAllSessionsFunc mocks the DeleteAllSessions method.
	DeleteAllSessionsFunc func(ctx context.Context) error

	// DeleteExpiredSessionsFunc mocks the DeleteExpiredSessions method.
	DeleteExpiredSessionsFunc func(ctx context.Context) (int64, error)

	// DeleteSessionFunc mocks the DeleteSession method.
	DeleteSessionFunc func(ctx context.Context, token string) error

	// DeleteSessionsByUsernameFunc mocks the DeleteSessionsByUsername method.
	DeleteSessionsByUsernameFunc func(ctx context.Context, username string) error

	// GetSessionFunc mocks the GetSession method.
	GetSessionFunc func(ctx context.Context, token string) (string, time.Time, error)

	// calls tracks calls to the methods.
	calls struct {
		// CreateSession holds details about calls to the CreateSession method.
		CreateSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
			// Username is the username argument value.
			Username string
			// ExpiresAt is the expiresAt argument value.
			ExpiresAt time.Time
		}
		// DeleteAllSessions holds details about calls to the DeleteAllSessions method.
		DeleteAllSessions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DeleteExpiredSessions holds details about calls to the DeleteExpiredSessions method.
		DeleteExpiredSessions []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DeleteSession holds details about calls to the DeleteSession method.
		DeleteSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// DeleteSessionsByUsername holds details about calls to the DeleteSessionsByUsername method.
		DeleteSessionsByUsername []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Username is the username argument value.
			Username string
		}
		// GetSession holds details about calls to the GetSession method.
		GetSession []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
	}
	lockCreateSession            sync.RWMutex
	lockDeleteAllSessions        sync.RWMutex
	lockDeleteExpiredSessions    sync.RWMutex
	lockDeleteSession            sync.RWMutex
	lockDeleteSessionsByUsername sync.RWMutex
	lockGetSession               sync.RWMutex
}

// CreateSession calls CreateSessionFunc.
func (mock *SessionStoreMock) CreateSession(ctx context.Context, token string, username string, expiresAt time.Time) error {
	if mock.CreateSessionFunc == nil {
		panic("SessionStoreMock.CreateSessionFunc: method is nil but SessionStore.CreateSession was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Token     string
		Username  string
		ExpiresAt time.Time
	}{
		Ctx:       ctx,
		Token:     token,
		Username:  username,
		ExpiresAt: expiresAt,
	}
	mock.lockCreateSession.Lock()
	mock.calls.CreateSession = append(mock.calls.CreateSession, callInfo)
	mock.lockCreateSession.Unlock()
	return mock.CreateSessionFunc(ctx, token, username, expiresAt)
}

// CreateSessionCalls gets all the calls that were made to CreateSession.
// Check the length with:
//
//	len(mockedSessionStore.CreateSessionCalls())
func (mock *SessionStoreMock) CreateSessionCalls() []struct {
	Ctx       context.Context
	Token     string
	Username  string
	ExpiresAt time.Time
} {
	var calls []struct {
		Ctx       context.Context
		Token     string
		Username  string
		ExpiresAt time.Time
	}
	mock.lockCreateSession.RLock()
	calls = mock.calls.CreateSession
	mock.lockCreateSession.RUnlock()
	return calls
}

// DeleteAllSessions calls DeleteAllSessionsFunc.
func (mock *SessionStoreMock) DeleteAllSessions(ctx context.Context) error {
	if mock.DeleteAllSessionsFunc == nil {
		panic("SessionStoreMock.DeleteAllSessionsFunc: method is nil but SessionStore.DeleteAllSessions was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDeleteAllSessions.Lock()
	mock.calls.DeleteAllSessions = append(mock.calls.DeleteAllSessions, callInfo)
	mock.lockDeleteAllSessions.Unlock()
	return mock.DeleteAllSessionsFunc(ctx)
}

// DeleteAllSessionsCalls gets all the calls that were made to DeleteAllSessions.
// Check the length with:
//
//	len(mockedSessionStore.DeleteAllSessionsCalls())
func (mock *SessionStoreMock) DeleteAllSessionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDeleteAllSessions.RLock()
	calls = mock.calls.DeleteAllSessions
	mock.lockDeleteAllSessions.RUnlock()
	return calls
}

// DeleteExpiredSessions calls DeleteExpiredSessionsFunc.
func (mock *SessionStoreMock) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	if mock.DeleteExpiredSessionsFunc == nil {
		panic("SessionStoreMock.DeleteExpiredSessionsFunc: method is nil but SessionStore.DeleteExpiredSessions was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockDeleteExpiredSessions.Lock()
	mock.calls.DeleteExpiredSessions = append(mock.calls.DeleteExpiredSessions, callInfo)
	mock.lockDeleteExpiredSessions.Unlock()
	return mock.DeleteExpiredSessionsFunc(ctx)
}

// DeleteExpiredSessionsCalls gets all the calls that were made to DeleteExpiredSessions.
// Check the length with:
//
//	len(mockedSessionStore.DeleteExpiredSessionsCalls())
func (mock *SessionStoreMock) DeleteExpiredSessionsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockDeleteExpiredSessions.RLock()
	calls = mock.calls.DeleteExpiredSessions
	mock.lockDeleteExpiredSessions.RUnlock()
	return calls
}

// DeleteSession calls DeleteSessionFunc.
func (mock *SessionStoreMock) DeleteSession(ctx context.Context, token string) error {
	if mock.DeleteSessionFunc == nil {
		panic("SessionStoreMock.DeleteSessionFunc: method is nil but SessionStore.DeleteSession was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockDeleteSession.Lock()
	mock.calls.DeleteSession = append(mock.calls.DeleteSession, callInfo)
	mock.lockDeleteSession.Unlock()
	return mock.DeleteSessionFunc(ctx, token)
}

// DeleteSessionCalls gets all the calls that were made to DeleteSession.
// Check the length with:
//
//	len(mockedSessionStore.DeleteSessionCalls())
func (mock *SessionStoreMock) DeleteSessionCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockDeleteSession.RLock()
	calls = mock.calls.DeleteSession
	mock.lockDeleteSession.RUnlock()
	return calls
}

// DeleteSessionsByUsername calls DeleteSessionsByUsernameFunc.
func (mock *SessionStoreMock) DeleteSessionsByUsername(ctx context.Context, username string) error {
	if mock.DeleteSessionsByUsernameFunc == nil {
		panic("SessionStoreMock.DeleteSessionsByUsernameFunc: method is nil but SessionStore.DeleteSessionsByUsername was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Username string
	}{
		Ctx:      ctx,
		Username: username,
	}
	mock.lockDeleteSessionsByUsername.Lock()
	mock.calls.DeleteSessionsByUsername = append(mock.calls.DeleteSessionsByUsername, callInfo)
	mock.lockDeleteSessionsByUsername.Unlock()
	return mock.DeleteSessionsByUsernameFunc(ctx, username)
}

// DeleteSessionsByUsernameCalls gets all the calls that were made to DeleteSessionsByUsername.
// Check the length with:
//
//	len(mockedSessionStore.DeleteSessionsByUsernameCalls())
func (mock *SessionStoreMock) DeleteSessionsByUsernameCalls() []struct {
	Ctx      context.Context
	Username string
} {
	var calls []struct {
		Ctx      context.Context
		Username string
	}
	mock.lockDeleteSessionsByUsername.RLock()
	calls = mock.calls.DeleteSessionsByUsername
	mock.lockDeleteSessionsByUsername.RUnlock()
	return calls
}

// GetSession calls GetSessionFunc.
func (mock *SessionStoreMock) GetSession(ctx context.Context, token string) (string, time.Time, error) {
	if mock.GetSessionFunc == nil {
		panic("SessionStoreMock.GetSessionFunc: method is nil but SessionStore.GetSession was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGetSession.Lock()
	mock.calls.GetSession = append(mock.calls.GetSession, callInfo)
	mock.lockGetSession.Unlock()
	return mock.GetSessionFunc(ctx, token)
}

// GetSessionCalls gets all the calls that were made to GetSession.
// Check the length with:
//
//	len(mockedSessionStore.GetSessionCalls())
func (mock *SessionStoreMock) GetSessionCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGetSession.RLock()
	calls = mock.calls.GetSession
	mock.lockGetSession.RUnlock()
	return calls
}
