version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      go-modules:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /lib/stash-js
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      stash-js:
        patterns:
          - "*"

  - package-ecosystem: cargo
    directory: /lib/stash-rust
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      stash-rust:
        patterns:
          - "*"

  - package-ecosystem: gradle
    directory: /lib/stash-java
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      stash-java:
        patterns:
          - "*"
