// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package git

import (
	"sync"
)

// EncryptorMock is a mock implementation of Encryptor.
//
//	func TestSomethingThatUsesEncryptor(t *testing.T) {
//
//		// make and configure a mocked Encryptor
//		mockedEncryptor := &EncryptorMock{
//			DecryptFunc: func(encrypted []byte) ([]byte, error) {
//				panic("mock out the Decrypt method")
//			},
//			EncryptFunc: func(value []byte) ([]byte, error) {
//				panic("mock out the Encrypt method")
//			},
//		}
//
//		// use mockedEncryptor in code that requires Encryptor
//		// and then make assertions.
//
//	}
type EncryptorMock struct {
	// DecryptFunc mocks the Decrypt method.
	DecryptFunc func(encrypted []byte) ([]byte, error)

	// EncryptFunc mocks the Encrypt method.
	EncryptFunc func(value []byte) ([]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Decrypt holds details about calls to the Decrypt method.
		Decrypt []struct {
			// Encrypted is the encrypted argument value.
			Encrypted []byte
		}
		// Encrypt holds details about calls to the Encrypt method.
		Encrypt []struct {
			// Value is the value argument value.
			Value []byte
		}
	}
	lockDecrypt sync.RWMutex
	lockEncrypt sync.RWMutex
}

// Decrypt calls DecryptFunc.
func (mock *EncryptorMock) Decrypt(encrypted []byte) ([]byte, error) {
	if mock.DecryptFunc == nil {
		panic("EncryptorMock.DecryptFunc: method is nil but Encryptor.Decrypt was just called")
	}
	callInfo := struct {
		Encrypted []byte
	}{
		Encrypted: encrypted,
	}
	mock.lockDecrypt.Lock()
	mock.calls.Decrypt = append(mock.calls.Decrypt, callInfo)
	mock.lockDecrypt.Unlock()
	return mock.DecryptFunc(encrypted)
}

// DecryptCalls gets all the calls that were made to Decrypt.
// Check the length with:
//
//	len(mockedEncryptor.DecryptCalls())
func (mock *EncryptorMock) DecryptCalls() []struct {
	Encrypted []byte
} {
	var calls []struct {
		Encrypted []byte
	}
	mock.lockDecrypt.RLock()
	calls = mock.calls.Decrypt
	mock.lockDecrypt.RUnlock()
	return calls
}

// Encrypt calls EncryptFunc.
func (mock *EncryptorMock) Encrypt(value []byte) ([]byte, error) {
	if mock.EncryptFunc == nil {
		panic("EncryptorMock.EncryptFunc: method is nil but Encryptor.Encrypt was just called")
	}
	callInfo := struct {
		Value []byte
	}{
		Value: value,
	}
	mock.lockEncrypt.Lock()
	mock.calls.Encrypt = append(mock.calls.Encrypt, callInfo)
	mock.lockEncrypt.Unlock()
	return mock.EncryptFunc(value)
}

// EncryptCalls gets all the calls that were made to Encrypt.
// Check the length with:
//
//	len(mockedEncryptor.EncryptCalls())
func (mock *EncryptorMock) EncryptCalls() []struct {
	Value []byte
} {
	var calls []struct {
		Value []byte
	}
	mock.lockEncrypt.RLock()
	calls = mock.calls.Encrypt
	mock.lockEncrypt.RUnlock()
	return calls
}
