// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/git"
)

// GitServiceMock is a mock implementation of web.GitService.
//
//	func TestSomethingThatUsesGitService(t *testing.T) {
//
//		// make and configure a mocked web.GitService
//		mockedGitService := &GitServiceMock{
//			CommitFunc: func(req git.CommitRequest) error {
//				panic("mock out the Commit method")
//			},
//			DeleteFunc: func(key string, author git.Author) error {
//				panic("mock out the Delete method")
//			},
//		}
//
//		// use mockedGitService in code that requires web.GitService
//		// and then make assertions.
//
//	}
type GitServiceMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func(req git.CommitRequest) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(key string, author git.Author) error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Req is the req argument value.
			Req git.CommitRequest
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Key is the key argument value.
			Key string
			// Author is the author argument value.
			Author git.Author
		}
	}
	lockCommit sync.RWMutex
	lockDelete sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *GitServiceMock) Commit(req git.CommitRequest) error {
	if mock.CommitFunc == nil {
		panic("GitServiceMock.CommitFunc: method is nil but GitService.Commit was just called")
	}
	callInfo := struct {
		Req git.CommitRequest
	}{
		Req: req,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(req)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedGitService.CommitCalls())
func (mock *GitServiceMock) CommitCalls() []struct {
	Req git.CommitRequest
} {
	var calls []struct {
		Req git.CommitRequest
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *GitServiceMock) Delete(key string, author git.Author) error {
	if mock.DeleteFunc == nil {
		panic("GitServiceMock.DeleteFunc: method is nil but GitService.Delete was just called")
	}
	callInfo := struct {
		Key    string
		Author git.Author
	}{
		Key:    key,
		Author: author,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(key, author)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedGitService.DeleteCalls())
func (mock *GitServiceMock) DeleteCalls() []struct {
	Key    string
	Author git.Author
} {
	var calls []struct {
		Key    string
		Author git.Author
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}
