// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
	"time"

	"github.com/umputun/stash/app/store"
)

// KVStoreMock is a mock implementation of web.KVStore.
//
//	func TestSomethingThatUsesKVStore(t *testing.T) {
//
//		// make and configure a mocked web.KVStore
//		mockedKVStore := &KVStoreMock{
//			DeleteFunc: func(ctx context.Context, key string) error {
//				panic("mock out the Delete method")
//			},
//			GetInfoFunc: func(ctx context.Context, key string) (store.KeyInfo, error) {
//				panic("mock out the GetInfo method")
//			},
//			GetWithFormatFunc: func(ctx context.Context, key string) ([]byte, string, error) {
//				panic("mock out the GetWithFormat method")
//			},
//			ListFunc: func(ctx context.Context) ([]store.KeyInfo, error) {
//				panic("mock out the List method")
//			},
//			SetFunc: func(ctx context.Context, key string, value []byte, format string) error {
//				panic("mock out the Set method")
//			},
//			SetWithVersionFunc: func(ctx context.Context, key string, value []byte, format string, expectedVersion time.Time) error {
//				panic("mock out the SetWithVersion method")
//			},
//		}
//
//		// use mockedKVStore in code that requires web.KVStore
//		// and then make assertions.
//
//	}
type KVStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(ctx context.Context, key string) error

	// GetInfoFunc mocks the GetInfo method.
	GetInfoFunc func(ctx context.Context, key string) (store.KeyInfo, error)

	// GetWithFormatFunc mocks the GetWithFormat method.
	GetWithFormatFunc func(ctx context.Context, key string) ([]byte, string, error)

	// ListFunc mocks the List method.
	ListFunc func(ctx context.Context) ([]store.KeyInfo, error)

	// SetFunc mocks the Set method.
	SetFunc func(ctx context.Context, key string, value []byte, format string) error

	// SetWithVersionFunc mocks the SetWithVersion method.
	SetWithVersionFunc func(ctx context.Context, key string, value []byte, format string, expectedVersion time.Time) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetInfo holds details about calls to the GetInfo method.
		GetInfo []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetWithFormat holds details about calls to the GetWithFormat method.
		GetWithFormat []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// List holds details about calls to the List method.
		List []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
			// Format is the format argument value.
			Format string
		}
		// SetWithVersion holds details about calls to the SetWithVersion method.
		SetWithVersion []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
			// Format is the format argument value.
			Format string
			// ExpectedVersion is the expectedVersion argument value.
			ExpectedVersion time.Time
		}
	}
	lockDelete         sync.RWMutex
	lockGetInfo        sync.RWMutex
	lockGetWithFormat  sync.RWMutex
	lockList           sync.RWMutex
	lockSet            sync.RWMutex
	lockSetWithVersion sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *KVStoreMock) Delete(ctx context.Context, key string) error {
	if mock.DeleteFunc == nil {
		panic("KVStoreMock.DeleteFunc: method is nil but KVStore.Delete was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(ctx, key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedKVStore.DeleteCalls())
func (mock *KVStoreMock) DeleteCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetInfo calls GetInfoFunc.
func (mock *KVStoreMock) GetInfo(ctx context.Context, key string) (store.KeyInfo, error) {
	if mock.GetInfoFunc == nil {
		panic("KVStoreMock.GetInfoFunc: method is nil but KVStore.GetInfo was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetInfo.Lock()
	mock.calls.GetInfo = append(mock.calls.GetInfo, callInfo)
	mock.lockGetInfo.Unlock()
	return mock.GetInfoFunc(ctx, key)
}

// GetInfoCalls gets all the calls that were made to GetInfo.
// Check the length with:
//
//	len(mockedKVStore.GetInfoCalls())
func (mock *KVStoreMock) GetInfoCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetInfo.RLock()
	calls = mock.calls.GetInfo
	mock.lockGetInfo.RUnlock()
	return calls
}

// GetWithFormat calls GetWithFormatFunc.
func (mock *KVStoreMock) GetWithFormat(ctx context.Context, key string) ([]byte, string, error) {
	if mock.GetWithFormatFunc == nil {
		panic("KVStoreMock.GetWithFormatFunc: method is nil but KVStore.GetWithFormat was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetWithFormat.Lock()
	mock.calls.GetWithFormat = append(mock.calls.GetWithFormat, callInfo)
	mock.lockGetWithFormat.Unlock()
	return mock.GetWithFormatFunc(ctx, key)
}

// GetWithFormatCalls gets all the calls that were made to GetWithFormat.
// Check the length with:
//
//	len(mockedKVStore.GetWithFormatCalls())
func (mock *KVStoreMock) GetWithFormatCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetWithFormat.RLock()
	calls = mock.calls.GetWithFormat
	mock.lockGetWithFormat.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *KVStoreMock) List(ctx context.Context) ([]store.KeyInfo, error) {
	if mock.ListFunc == nil {
		panic("KVStoreMock.ListFunc: method is nil but KVStore.List was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc(ctx)
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedKVStore.ListCalls())
func (mock *KVStoreMock) ListCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *KVStoreMock) Set(ctx context.Context, key string, value []byte, format string) error {
	if mock.SetFunc == nil {
		panic("KVStoreMock.SetFunc: method is nil but KVStore.Set was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Key    string
		Value  []byte
		Format string
	}{
		Ctx:    ctx,
		Key:    key,
		Value:  value,
		Format: format,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(ctx, key, value, format)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedKVStore.SetCalls())
func (mock *KVStoreMock) SetCalls() []struct {
	Ctx    context.Context
	Key    string
	Value  []byte
	Format string
} {
	var calls []struct {
		Ctx    context.Context
		Key    string
		Value  []byte
		Format string
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}

// SetWithVersion calls SetWithVersionFunc.
func (mock *KVStoreMock) SetWithVersion(ctx context.Context, key string, value []byte, format string, expectedVersion time.Time) error {
	if mock.SetWithVersionFunc == nil {
		panic("KVStoreMock.SetWithVersionFunc: method is nil but KVStore.SetWithVersion was just called")
	}
	callInfo := struct {
		Ctx             context.Context
		Key             string
		Value           []byte
		Format          string
		ExpectedVersion time.Time
	}{
		Ctx:             ctx,
		Key:             key,
		Value:           value,
		Format:          format,
		ExpectedVersion: expectedVersion,
	}
	mock.lockSetWithVersion.Lock()
	mock.calls.SetWithVersion = append(mock.calls.SetWithVersion, callInfo)
	mock.lockSetWithVersion.Unlock()
	return mock.SetWithVersionFunc(ctx, key, value, format, expectedVersion)
}

// SetWithVersionCalls gets all the calls that were made to SetWithVersion.
// Check the length with:
//
//	len(mockedKVStore.SetWithVersionCalls())
func (mock *KVStoreMock) SetWithVersionCalls() []struct {
	Ctx             context.Context
	Key             string
	Value           []byte
	Format          string
	ExpectedVersion time.Time
} {
	var calls []struct {
		Ctx             context.Context
		Key             string
		Value           []byte
		Format          string
		ExpectedVersion time.Time
	}
	mock.lockSetWithVersion.RLock()
	calls = mock.calls.SetWithVersion
	mock.lockSetWithVersion.RUnlock()
	return calls
}
