// Code generated by enum generator; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// ActorType is the exported type for the enum
type ActorType struct {
	name  string
	value int
}

func (e ActorType) String() string { return e.name }

// Index returns the underlying integer value
func (e ActorType) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e ActorType) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *ActorType) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseActorType(string(text))
	return err
}

// _actorTypeParseMap is used for efficient string to enum conversion
var _actorTypeParseMap = map[string]ActorType{
	"user":   ActorTypeUser,
	"token":  ActorTypeToken,
	"public": ActorTypePublic,
}

// ParseActorType converts string to actorType enum value.
// Parsing is always case-insensitive.
func ParseActorType(v string) (ActorType, error) {
	if val, ok := _actorTypeParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return ActorType{}, fmt.Errorf("invalid actorType: %s", v)
}

// MustActorType is like ParseActorType but panics if string is invalid
func MustActorType(v string) ActorType {
	r, err := ParseActorType(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for actorType values
var (
	ActorTypeUser   = ActorType{name: "user", value: 0}
	ActorTypeToken  = ActorType{name: "token", value: 1}
	ActorTypePublic = ActorType{name: "public", value: 2}
)

// ActorTypeValues contains all possible enum values
var ActorTypeValues = []ActorType{
	ActorTypeUser,
	ActorTypeToken,
	ActorTypePublic,
}

// ActorTypeNames contains all possible enum names
var ActorTypeNames = []string{
	"user",
	"token",
	"public",
}

// ActorTypeIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all ActorType values in declaration order. Example:
//
//	for v := range ActorTypeIter() {
//	    // use v
//	}
func ActorTypeIter() func(yield func(ActorType) bool) {
	return func(yield func(ActorType) bool) {
		for _, v := range ActorTypeValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ actorType = actorType(0)
	// This avoids "defined but not used" linter error for actorTypeUser
	var _ actorType = actorTypeUser
	// This avoids "defined but not used" linter error for actorTypeToken
	var _ actorType = actorTypeToken
	// This avoids "defined but not used" linter error for actorTypePublic
	var _ actorType = actorTypePublic
	return true
}()
