// Code generated by enum generator; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// DbType is the exported type for the enum
type DbType struct {
	name  string
	value int
}

func (e DbType) String() string { return e.name }

// Index returns the underlying integer value
func (e DbType) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e DbType) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *DbType) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseDbType(string(text))
	return err
}

// _dbTypeParseMap is used for efficient string to enum conversion
var _dbTypeParseMap = map[string]DbType{
	"sqlite":   DbTypeSQLite,
	"postgres": DbTypePostgres,
}

// ParseDbType converts string to dbType enum value.
// Parsing is always case-insensitive.
func ParseDbType(v string) (DbType, error) {
	if val, ok := _dbTypeParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return DbType{}, fmt.Errorf("invalid dbType: %s", v)
}

// MustDbType is like ParseDbType but panics if string is invalid
func MustDbType(v string) DbType {
	r, err := ParseDbType(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for dbType values
var (
	DbTypeSQLite   = DbType{name: "sqlite", value: 0}
	DbTypePostgres = DbType{name: "postgres", value: 1}
)

// DbTypeValues contains all possible enum values
var DbTypeValues = []DbType{
	DbTypeSQLite,
	DbTypePostgres,
}

// DbTypeNames contains all possible enum names
var DbTypeNames = []string{
	"sqlite",
	"postgres",
}

// DbTypeIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all DbType values in declaration order. Example:
//
//	for v := range DbTypeIter() {
//	    // use v
//	}
func DbTypeIter() func(yield func(DbType) bool) {
	return func(yield func(DbType) bool) {
		for _, v := range DbTypeValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ dbType = dbType(0)
	// This avoids "defined but not used" linter error for dbTypeSQLite
	var _ dbType = dbTypeSQLite
	// This avoids "defined but not used" linter error for dbTypePostgres
	var _ dbType = dbTypePostgres
	return true
}()
