// Code generated by enum generator; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// SecretsFilter is the exported type for the enum
type SecretsFilter struct {
	name  string
	value int
}

func (e SecretsFilter) String() string { return e.name }

// Index returns the underlying integer value
func (e SecretsFilter) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e SecretsFilter) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *SecretsFilter) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseSecretsFilter(string(text))
	return err
}

// _secretsFilterParseMap is used for efficient string to enum conversion
var _secretsFilterParseMap = map[string]SecretsFilter{
	"all":         SecretsFilterAll,
	"secretsonly": SecretsFilterSecretsOnly,
	"secrets":     SecretsFilterSecretsOnly,
	"true":        SecretsFilterSecretsOnly,
	"keysonly":    SecretsFilterKeysOnly,
	"keys":        SecretsFilterKeysOnly,
	"false":       SecretsFilterKeysOnly,
}

// ParseSecretsFilter converts string to secretsFilter enum value.
// Parsing is always case-insensitive.
func ParseSecretsFilter(v string) (SecretsFilter, error) {
	if val, ok := _secretsFilterParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return SecretsFilter{}, fmt.Errorf("invalid secretsFilter: %s", v)
}

// MustSecretsFilter is like ParseSecretsFilter but panics if string is invalid
func MustSecretsFilter(v string) SecretsFilter {
	r, err := ParseSecretsFilter(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for secretsFilter values
var (
	SecretsFilterAll         = SecretsFilter{name: "all", value: 0}
	SecretsFilterSecretsOnly = SecretsFilter{name: "secretsonly", value: 1}
	SecretsFilterKeysOnly    = SecretsFilter{name: "keysonly", value: 2}
)

// SecretsFilterValues contains all possible enum values
var SecretsFilterValues = []SecretsFilter{
	SecretsFilterAll,
	SecretsFilterSecretsOnly,
	SecretsFilterKeysOnly,
}

// SecretsFilterNames contains all possible enum names
var SecretsFilterNames = []string{
	"all",
	"secretsonly",
	"keysonly",
}

// SecretsFilterIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all SecretsFilter values in declaration order. Example:
//
//	for v := range SecretsFilterIter() {
//	    // use v
//	}
func SecretsFilterIter() func(yield func(SecretsFilter) bool) {
	return func(yield func(SecretsFilter) bool) {
		for _, v := range SecretsFilterValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ secretsFilter = secretsFilter(0)
	// This avoids "defined but not used" linter error for secretsFilterAll
	var _ secretsFilter = secretsFilterAll
	// This avoids "defined but not used" linter error for secretsFilterSecretsOnly
	var _ secretsFilter = secretsFilterSecretsOnly
	// This avoids "defined but not used" linter error for secretsFilterKeysOnly
	var _ secretsFilter = secretsFilterKeysOnly
	return true
}()
