// Code generated by enum generator; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// SortMode is the exported type for the enum
type SortMode struct {
	name  string
	value int
}

func (e SortMode) String() string { return e.name }

// Index returns the underlying integer value
func (e SortMode) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e SortMode) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *SortMode) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseSortMode(string(text))
	return err
}

// _sortModeParseMap is used for efficient string to enum conversion
var _sortModeParseMap = map[string]SortMode{
	"updated": SortModeUpdated,
	"key":     SortModeKey,
	"size":    SortModeSize,
	"created": SortModeCreated,
}

// ParseSortMode converts string to sortMode enum value.
// Parsing is always case-insensitive.
func ParseSortMode(v string) (SortMode, error) {
	if val, ok := _sortModeParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return SortMode{}, fmt.Errorf("invalid sortMode: %s", v)
}

// MustSortMode is like ParseSortMode but panics if string is invalid
func MustSortMode(v string) SortMode {
	r, err := ParseSortMode(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for sortMode values
var (
	SortModeUpdated = SortMode{name: "updated", value: 0}
	SortModeKey     = SortMode{name: "key", value: 1}
	SortModeSize    = SortMode{name: "size", value: 2}
	SortModeCreated = SortMode{name: "created", value: 3}
)

// SortModeValues contains all possible enum values
var SortModeValues = []SortMode{
	SortModeUpdated,
	SortModeKey,
	SortModeSize,
	SortModeCreated,
}

// SortModeNames contains all possible enum names
var SortModeNames = []string{
	"updated",
	"key",
	"size",
	"created",
}

// SortModeIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all SortMode values in declaration order. Example:
//
//	for v := range SortModeIter() {
//	    // use v
//	}
func SortModeIter() func(yield func(SortMode) bool) {
	return func(yield func(SortMode) bool) {
		for _, v := range SortModeValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ sortMode = sortMode(0)
	// This avoids "defined but not used" linter error for sortModeUpdated
	var _ sortMode = sortModeUpdated
	// This avoids "defined but not used" linter error for sortModeKey
	var _ sortMode = sortModeKey
	// This avoids "defined but not used" linter error for sortModeSize
	var _ sortMode = sortModeSize
	// This avoids "defined but not used" linter error for sortModeCreated
	var _ sortMode = sortModeCreated
	return true
}()
