// Code generated by enum generator; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// Theme is the exported type for the enum
type Theme struct {
	name  string
	value int
}

func (e Theme) String() string { return e.name }

// Index returns the underlying integer value
func (e Theme) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e Theme) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *Theme) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseTheme(string(text))
	return err
}

// _themeParseMap is used for efficient string to enum conversion
var _themeParseMap = map[string]Theme{
	"system": ThemeSystem,
	"light":  ThemeLight,
	"dark":   ThemeDark,
}

// ParseTheme converts string to theme enum value.
// Parsing is always case-insensitive.
func ParseTheme(v string) (Theme, error) {
	if val, ok := _themeParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return Theme{}, fmt.Errorf("invalid theme: %s", v)
}

// MustTheme is like ParseTheme but panics if string is invalid
func MustTheme(v string) Theme {
	r, err := ParseTheme(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for theme values
var (
	ThemeSystem = Theme{name: "system", value: 0}
	ThemeLight  = Theme{name: "light", value: 1}
	ThemeDark   = Theme{name: "dark", value: 2}
)

// ThemeValues contains all possible enum values
var ThemeValues = []Theme{
	ThemeSystem,
	ThemeLight,
	ThemeDark,
}

// ThemeNames contains all possible enum names
var ThemeNames = []string{
	"system",
	"light",
	"dark",
}

// ThemeIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all Theme values in declaration order. Example:
//
//	for v := range ThemeIter() {
//	    // use v
//	}
func ThemeIter() func(yield func(Theme) bool) {
	return func(yield func(Theme) bool) {
		for _, v := range ThemeValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ theme = theme(0)
	// This avoids "defined but not used" linter error for themeSystem
	var _ theme = themeSystem
	// This avoids "defined but not used" linter error for themeLight
	var _ theme = themeLight
	// This avoids "defined but not used" linter error for themeDark
	var _ theme = themeDark
	return true
}()
