// Code generated by enum generator; DO NOT EDIT.
package enum

import (
	"fmt"
	"strings"
)

// ViewMode is the exported type for the enum
type ViewMode struct {
	name  string
	value int
}

func (e ViewMode) String() string { return e.name }

// Index returns the underlying integer value
func (e ViewMode) Index() int { return e.value }

// MarshalText implements encoding.TextMarshaler
func (e ViewMode) MarshalText() ([]byte, error) {
	return []byte(e.name), nil
}

// UnmarshalText implements encoding.TextUnmarshaler
func (e *ViewMode) UnmarshalText(text []byte) error {
	var err error
	*e, err = ParseViewMode(string(text))
	return err
}

// _viewModeParseMap is used for efficient string to enum conversion
var _viewModeParseMap = map[string]ViewMode{
	"grid":  ViewModeGrid,
	"cards": ViewModeCards,
}

// ParseViewMode converts string to viewMode enum value.
// Parsing is always case-insensitive.
func ParseViewMode(v string) (ViewMode, error) {
	if val, ok := _viewModeParseMap[strings.ToLower(v)]; ok {
		return val, nil
	}
	return ViewMode{}, fmt.Errorf("invalid viewMode: %s", v)
}

// MustViewMode is like ParseViewMode but panics if string is invalid
func MustViewMode(v string) ViewMode {
	r, err := ParseViewMode(v)
	if err != nil {
		panic(err)
	}
	return r
}

// Public constants for viewMode values
var (
	ViewModeGrid  = ViewMode{name: "grid", value: 0}
	ViewModeCards = ViewMode{name: "cards", value: 1}
)

// ViewModeValues contains all possible enum values
var ViewModeValues = []ViewMode{
	ViewModeGrid,
	ViewModeCards,
}

// ViewModeNames contains all possible enum names
var ViewModeNames = []string{
	"grid",
	"cards",
}

// ViewModeIter returns a function compatible with Go 1.23's range-over-func syntax.
// It yields all ViewMode values in declaration order. Example:
//
//	for v := range ViewModeIter() {
//	    // use v
//	}
func ViewModeIter() func(yield func(ViewMode) bool) {
	return func(yield func(ViewMode) bool) {
		for _, v := range ViewModeValues {
			if !yield(v) {
				break
			}
		}
	}
}

// These variables are used to prevent the compiler from reporting unused errors
// for the original enum constants. They are intentionally placed in a var block
// that is compiled away by the Go compiler.
var _ = func() bool {
	var _ viewMode = viewMode(0)
	// This avoids "defined but not used" linter error for viewModeGrid
	var _ viewMode = viewModeGrid
	// This avoids "defined but not used" linter error for viewModeCards
	var _ viewMode = viewModeCards
	return true
}()
