// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"net/http"
	"sync"
)

// AuthMock is a mock implementation of audit.Auth.
//
//	func TestSomethingThatUsesAuth(t *testing.T) {
//
//		// make and configure a mocked audit.Auth
//		mockedAuth := &AuthMock{
//			GetRequestActorFunc: func(r *http.Request) (string, string) {
//				panic("mock out the GetRequestActor method")
//			},
//			IsRequestAdminFunc: func(r *http.Request) bool {
//				panic("mock out the IsRequestAdmin method")
//			},
//		}
//
//		// use mockedAuth in code that requires audit.Auth
//		// and then make assertions.
//
//	}
type AuthMock struct {
	// GetRequestActorFunc mocks the GetRequestActor method.
	GetRequestActorFunc func(r *http.Request) (string, string)

	// IsRequestAdminFunc mocks the IsRequestAdmin method.
	IsRequestAdminFunc func(r *http.Request) bool

	// calls tracks calls to the methods.
	calls struct {
		// GetRequestActor holds details about calls to the GetRequestActor method.
		GetRequestActor []struct {
			// R is the r argument value.
			R *http.Request
		}
		// IsRequestAdmin holds details about calls to the IsRequestAdmin method.
		IsRequestAdmin []struct {
			// R is the r argument value.
			R *http.Request
		}
	}
	lockGetRequestActor sync.RWMutex
	lockIsRequestAdmin  sync.RWMutex
}

// GetRequestActor calls GetRequestActorFunc.
func (mock *AuthMock) GetRequestActor(r *http.Request) (string, string) {
	if mock.GetRequestActorFunc == nil {
		panic("AuthMock.GetRequestActorFunc: method is nil but Auth.GetRequestActor was just called")
	}
	callInfo := struct {
		R *http.Request
	}{
		R: r,
	}
	mock.lockGetRequestActor.Lock()
	mock.calls.GetRequestActor = append(mock.calls.GetRequestActor, callInfo)
	mock.lockGetRequestActor.Unlock()
	return mock.GetRequestActorFunc(r)
}

// GetRequestActorCalls gets all the calls that were made to GetRequestActor.
// Check the length with:
//
//	len(mockedAuth.GetRequestActorCalls())
func (mock *AuthMock) GetRequestActorCalls() []struct {
	R *http.Request
} {
	var calls []struct {
		R *http.Request
	}
	mock.lockGetRequestActor.RLock()
	calls = mock.calls.GetRequestActor
	mock.lockGetRequestActor.RUnlock()
	return calls
}

// IsRequestAdmin calls IsRequestAdminFunc.
func (mock *AuthMock) IsRequestAdmin(r *http.Request) bool {
	if mock.IsRequestAdminFunc == nil {
		panic("AuthMock.IsRequestAdminFunc: method is nil but Auth.IsRequestAdmin was just called")
	}
	callInfo := struct {
		R *http.Request
	}{
		R: r,
	}
	mock.lockIsRequestAdmin.Lock()
	mock.calls.IsRequestAdmin = append(mock.calls.IsRequestAdmin, callInfo)
	mock.lockIsRequestAdmin.Unlock()
	return mock.IsRequestAdminFunc(r)
}

// IsRequestAdminCalls gets all the calls that were made to IsRequestAdmin.
// Check the length with:
//
//	len(mockedAuth.IsRequestAdminCalls())
func (mock *AuthMock) IsRequestAdminCalls() []struct {
	R *http.Request
} {
	var calls []struct {
		R *http.Request
	}
	mock.lockIsRequestAdmin.RLock()
	calls = mock.calls.IsRequestAdmin
	mock.lockIsRequestAdmin.RUnlock()
	return calls
}
