// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"

	"github.com/umputun/stash/app/store"
)

// StoreMock is a mock implementation of audit.Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a mocked audit.Store
//		mockedStore := &StoreMock{
//			LogAuditFunc: func(ctx context.Context, entry store.AuditEntry) error {
//				panic("mock out the LogAudit method")
//			},
//			QueryAuditFunc: func(ctx context.Context, q store.AuditQuery) ([]store.AuditEntry, int, error) {
//				panic("mock out the QueryAudit method")
//			},
//		}
//
//		// use mockedStore in code that requires audit.Store
//		// and then make assertions.
//
//	}
type StoreMock struct {
	// LogAuditFunc mocks the LogAudit method.
	LogAuditFunc func(ctx context.Context, entry store.AuditEntry) error

	// QueryAuditFunc mocks the QueryAudit method.
	QueryAuditFunc func(ctx context.Context, q store.AuditQuery) ([]store.AuditEntry, int, error)

	// calls tracks calls to the methods.
	calls struct {
		// LogAudit holds details about calls to the LogAudit method.
		LogAudit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Entry is the entry argument value.
			Entry store.AuditEntry
		}
		// QueryAudit holds details about calls to the QueryAudit method.
		QueryAudit []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Q is the q argument value.
			Q store.AuditQuery
		}
	}
	lockLogAudit   sync.RWMutex
	lockQueryAudit sync.RWMutex
}

// LogAudit calls LogAuditFunc.
func (mock *StoreMock) LogAudit(ctx context.Context, entry store.AuditEntry) error {
	if mock.LogAuditFunc == nil {
		panic("StoreMock.LogAuditFunc: method is nil but Store.LogAudit was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Entry store.AuditEntry
	}{
		Ctx:   ctx,
		Entry: entry,
	}
	mock.lockLogAudit.Lock()
	mock.calls.LogAudit = append(mock.calls.LogAudit, callInfo)
	mock.lockLogAudit.Unlock()
	return mock.LogAuditFunc(ctx, entry)
}

// LogAuditCalls gets all the calls that were made to LogAudit.
// Check the length with:
//
//	len(mockedStore.LogAuditCalls())
func (mock *StoreMock) LogAuditCalls() []struct {
	Ctx   context.Context
	Entry store.AuditEntry
} {
	var calls []struct {
		Ctx   context.Context
		Entry store.AuditEntry
	}
	mock.lockLogAudit.RLock()
	calls = mock.calls.LogAudit
	mock.lockLogAudit.RUnlock()
	return calls
}

// QueryAudit calls QueryAuditFunc.
func (mock *StoreMock) QueryAudit(ctx context.Context, q store.AuditQuery) ([]store.AuditEntry, int, error) {
	if mock.QueryAuditFunc == nil {
		panic("StoreMock.QueryAuditFunc: method is nil but Store.QueryAudit was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Q   store.AuditQuery
	}{
		Ctx: ctx,
		Q:   q,
	}
	mock.lockQueryAudit.Lock()
	mock.calls.QueryAudit = append(mock.calls.QueryAudit, callInfo)
	mock.lockQueryAudit.Unlock()
	return mock.QueryAuditFunc(ctx, q)
}

// QueryAuditCalls gets all the calls that were made to QueryAudit.
// Check the length with:
//
//	len(mockedStore.QueryAuditCalls())
func (mock *StoreMock) QueryAuditCalls() []struct {
	Ctx context.Context
	Q   store.AuditQuery
} {
	var calls []struct {
		Ctx context.Context
		Q   store.AuditQuery
	}
	mock.lockQueryAudit.RLock()
	calls = mock.calls.QueryAudit
	mock.lockQueryAudit.RUnlock()
	return calls
}
