// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"sync"
)

// AuthProviderMock is a mock implementation of api.AuthProvider.
//
//	func TestSomethingThatUsesAuthProvider(t *testing.T) {
//
//		// make and configure a mocked api.AuthProvider
//		mockedAuthProvider := &AuthProviderMock{
//			EnabledFunc: func() bool {
//				panic("mock out the Enabled method")
//			},
//			FilterPublicKeysFunc: func(keys []string) []string {
//				panic("mock out the FilterPublicKeys method")
//			},
//			FilterTokenKeysFunc: func(token string, keys []string) []string {
//				panic("mock out the FilterTokenKeys method")
//			},
//			FilterUserKeysFunc: func(username string, keys []string) []string {
//				panic("mock out the FilterUserKeys method")
//			},
//			GetSessionUserFunc: func(ctx context.Context, token string) (string, bool) {
//				panic("mock out the GetSessionUser method")
//			},
//			HasTokenACLFunc: func(token string) bool {
//				panic("mock out the HasTokenACL method")
//			},
//		}
//
//		// use mockedAuthProvider in code that requires api.AuthProvider
//		// and then make assertions.
//
//	}
type AuthProviderMock struct {
	// EnabledFunc mocks the Enabled method.
	EnabledFunc func() bool

	// FilterPublicKeysFunc mocks the FilterPublicKeys method.
	FilterPublicKeysFunc func(keys []string) []string

	// FilterTokenKeysFunc mocks the FilterTokenKeys method.
	FilterTokenKeysFunc func(token string, keys []string) []string

	// FilterUserKeysFunc mocks the FilterUserKeys method.
	FilterUserKeysFunc func(username string, keys []string) []string

	// GetSessionUserFunc mocks the GetSessionUser method.
	GetSessionUserFunc func(ctx context.Context, token string) (string, bool)

	// HasTokenACLFunc mocks the HasTokenACL method.
	HasTokenACLFunc func(token string) bool

	// calls tracks calls to the methods.
	calls struct {
		// Enabled holds details about calls to the Enabled method.
		Enabled []struct {
		}
		// FilterPublicKeys holds details about calls to the FilterPublicKeys method.
		FilterPublicKeys []struct {
			// Keys is the keys argument value.
			Keys []string
		}
		// FilterTokenKeys holds details about calls to the FilterTokenKeys method.
		FilterTokenKeys []struct {
			// Token is the token argument value.
			Token string
			// Keys is the keys argument value.
			Keys []string
		}
		// FilterUserKeys holds details about calls to the FilterUserKeys method.
		FilterUserKeys []struct {
			// Username is the username argument value.
			Username string
			// Keys is the keys argument value.
			Keys []string
		}
		// GetSessionUser holds details about calls to the GetSessionUser method.
		GetSessionUser []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Token is the token argument value.
			Token string
		}
		// HasTokenACL holds details about calls to the HasTokenACL method.
		HasTokenACL []struct {
			// Token is the token argument value.
			Token string
		}
	}
	lockEnabled          sync.RWMutex
	lockFilterPublicKeys sync.RWMutex
	lockFilterTokenKeys  sync.RWMutex
	lockFilterUserKeys   sync.RWMutex
	lockGetSessionUser   sync.RWMutex
	lockHasTokenACL      sync.RWMutex
}

// Enabled calls EnabledFunc.
func (mock *AuthProviderMock) Enabled() bool {
	if mock.EnabledFunc == nil {
		panic("AuthProviderMock.EnabledFunc: method is nil but AuthProvider.Enabled was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEnabled.Lock()
	mock.calls.Enabled = append(mock.calls.Enabled, callInfo)
	mock.lockEnabled.Unlock()
	return mock.EnabledFunc()
}

// EnabledCalls gets all the calls that were made to Enabled.
// Check the length with:
//
//	len(mockedAuthProvider.EnabledCalls())
func (mock *AuthProviderMock) EnabledCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEnabled.RLock()
	calls = mock.calls.Enabled
	mock.lockEnabled.RUnlock()
	return calls
}

// FilterPublicKeys calls FilterPublicKeysFunc.
func (mock *AuthProviderMock) FilterPublicKeys(keys []string) []string {
	if mock.FilterPublicKeysFunc == nil {
		panic("AuthProviderMock.FilterPublicKeysFunc: method is nil but AuthProvider.FilterPublicKeys was just called")
	}
	callInfo := struct {
		Keys []string
	}{
		Keys: keys,
	}
	mock.lockFilterPublicKeys.Lock()
	mock.calls.FilterPublicKeys = append(mock.calls.FilterPublicKeys, callInfo)
	mock.lockFilterPublicKeys.Unlock()
	return mock.FilterPublicKeysFunc(keys)
}

// FilterPublicKeysCalls gets all the calls that were made to FilterPublicKeys.
// Check the length with:
//
//	len(mockedAuthProvider.FilterPublicKeysCalls())
func (mock *AuthProviderMock) FilterPublicKeysCalls() []struct {
	Keys []string
} {
	var calls []struct {
		Keys []string
	}
	mock.lockFilterPublicKeys.RLock()
	calls = mock.calls.FilterPublicKeys
	mock.lockFilterPublicKeys.RUnlock()
	return calls
}

// FilterTokenKeys calls FilterTokenKeysFunc.
func (mock *AuthProviderMock) FilterTokenKeys(token string, keys []string) []string {
	if mock.FilterTokenKeysFunc == nil {
		panic("AuthProviderMock.FilterTokenKeysFunc: method is nil but AuthProvider.FilterTokenKeys was just called")
	}
	callInfo := struct {
		Token string
		Keys  []string
	}{
		Token: token,
		Keys:  keys,
	}
	mock.lockFilterTokenKeys.Lock()
	mock.calls.FilterTokenKeys = append(mock.calls.FilterTokenKeys, callInfo)
	mock.lockFilterTokenKeys.Unlock()
	return mock.FilterTokenKeysFunc(token, keys)
}

// FilterTokenKeysCalls gets all the calls that were made to FilterTokenKeys.
// Check the length with:
//
//	len(mockedAuthProvider.FilterTokenKeysCalls())
func (mock *AuthProviderMock) FilterTokenKeysCalls() []struct {
	Token string
	Keys  []string
} {
	var calls []struct {
		Token string
		Keys  []string
	}
	mock.lockFilterTokenKeys.RLock()
	calls = mock.calls.FilterTokenKeys
	mock.lockFilterTokenKeys.RUnlock()
	return calls
}

// FilterUserKeys calls FilterUserKeysFunc.
func (mock *AuthProviderMock) FilterUserKeys(username string, keys []string) []string {
	if mock.FilterUserKeysFunc == nil {
		panic("AuthProviderMock.FilterUserKeysFunc: method is nil but AuthProvider.FilterUserKeys was just called")
	}
	callInfo := struct {
		Username string
		Keys     []string
	}{
		Username: username,
		Keys:     keys,
	}
	mock.lockFilterUserKeys.Lock()
	mock.calls.FilterUserKeys = append(mock.calls.FilterUserKeys, callInfo)
	mock.lockFilterUserKeys.Unlock()
	return mock.FilterUserKeysFunc(username, keys)
}

// FilterUserKeysCalls gets all the calls that were made to FilterUserKeys.
// Check the length with:
//
//	len(mockedAuthProvider.FilterUserKeysCalls())
func (mock *AuthProviderMock) FilterUserKeysCalls() []struct {
	Username string
	Keys     []string
} {
	var calls []struct {
		Username string
		Keys     []string
	}
	mock.lockFilterUserKeys.RLock()
	calls = mock.calls.FilterUserKeys
	mock.lockFilterUserKeys.RUnlock()
	return calls
}

// GetSessionUser calls GetSessionUserFunc.
func (mock *AuthProviderMock) GetSessionUser(ctx context.Context, token string) (string, bool) {
	if mock.GetSessionUserFunc == nil {
		panic("AuthProviderMock.GetSessionUserFunc: method is nil but AuthProvider.GetSessionUser was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Token string
	}{
		Ctx:   ctx,
		Token: token,
	}
	mock.lockGetSessionUser.Lock()
	mock.calls.GetSessionUser = append(mock.calls.GetSessionUser, callInfo)
	mock.lockGetSessionUser.Unlock()
	return mock.GetSessionUserFunc(ctx, token)
}

// GetSessionUserCalls gets all the calls that were made to GetSessionUser.
// Check the length with:
//
//	len(mockedAuthProvider.GetSessionUserCalls())
func (mock *AuthProviderMock) GetSessionUserCalls() []struct {
	Ctx   context.Context
	Token string
} {
	var calls []struct {
		Ctx   context.Context
		Token string
	}
	mock.lockGetSessionUser.RLock()
	calls = mock.calls.GetSessionUser
	mock.lockGetSessionUser.RUnlock()
	return calls
}

// HasTokenACL calls HasTokenACLFunc.
func (mock *AuthProviderMock) HasTokenACL(token string) bool {
	if mock.HasTokenACLFunc == nil {
		panic("AuthProviderMock.HasTokenACLFunc: method is nil but AuthProvider.HasTokenACL was just called")
	}
	callInfo := struct {
		Token string
	}{
		Token: token,
	}
	mock.lockHasTokenACL.Lock()
	mock.calls.HasTokenACL = append(mock.calls.HasTokenACL, callInfo)
	mock.lockHasTokenACL.Unlock()
	return mock.HasTokenACLFunc(token)
}

// HasTokenACLCalls gets all the calls that were made to HasTokenACL.
// Check the length with:
//
//	len(mockedAuthProvider.HasTokenACLCalls())
func (mock *AuthProviderMock) HasTokenACLCalls() []struct {
	Token string
} {
	var calls []struct {
		Token string
	}
	mock.lockHasTokenACL.RLock()
	calls = mock.calls.HasTokenACL
	mock.lockHasTokenACL.RUnlock()
	return calls
}
