// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/enum"
)

// EventPublisherMock is a mock implementation of api.EventPublisher.
//
//	func TestSomethingThatUsesEventPublisher(t *testing.T) {
//
//		// make and configure a mocked api.EventPublisher
//		mockedEventPublisher := &EventPublisherMock{
//			PublishFunc: func(key string, action enum.AuditAction)  {
//				panic("mock out the Publish method")
//			},
//		}
//
//		// use mockedEventPublisher in code that requires api.EventPublisher
//		// and then make assertions.
//
//	}
type EventPublisherMock struct {
	// PublishFunc mocks the Publish method.
	PublishFunc func(key string, action enum.AuditAction)

	// calls tracks calls to the methods.
	calls struct {
		// Publish holds details about calls to the Publish method.
		Publish []struct {
			// Key is the key argument value.
			Key string
			// Action is the action argument value.
			Action enum.AuditAction
		}
	}
	lockPublish sync.RWMutex
}

// Publish calls PublishFunc.
func (mock *EventPublisherMock) Publish(key string, action enum.AuditAction) {
	if mock.PublishFunc == nil {
		panic("EventPublisherMock.PublishFunc: method is nil but EventPublisher.Publish was just called")
	}
	callInfo := struct {
		Key    string
		Action enum.AuditAction
	}{
		Key:    key,
		Action: action,
	}
	mock.lockPublish.Lock()
	mock.calls.Publish = append(mock.calls.Publish, callInfo)
	mock.lockPublish.Unlock()
	mock.PublishFunc(key, action)
}

// PublishCalls gets all the calls that were made to Publish.
// Check the length with:
//
//	len(mockedEventPublisher.PublishCalls())
func (mock *EventPublisherMock) PublishCalls() []struct {
	Key    string
	Action enum.AuditAction
} {
	var calls []struct {
		Key    string
		Action enum.AuditAction
	}
	mock.lockPublish.RLock()
	calls = mock.calls.Publish
	mock.lockPublish.RUnlock()
	return calls
}
