// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"
)

// FormatValidatorMock is a mock implementation of api.FormatValidator.
//
//	func TestSomethingThatUsesFormatValidator(t *testing.T) {
//
//		// make and configure a mocked api.FormatValidator
//		mockedFormatValidator := &FormatValidatorMock{
//			IsValidFormatFunc: func(format string) bool {
//				panic("mock out the IsValidFormat method")
//			},
//		}
//
//		// use mockedFormatValidator in code that requires api.FormatValidator
//		// and then make assertions.
//
//	}
type FormatValidatorMock struct {
	// IsValidFormatFunc mocks the IsValidFormat method.
	IsValidFormatFunc func(format string) bool

	// calls tracks calls to the methods.
	calls struct {
		// IsValidFormat holds details about calls to the IsValidFormat method.
		IsValidFormat []struct {
			// Format is the format argument value.
			Format string
		}
	}
	lockIsValidFormat sync.RWMutex
}

// IsValidFormat calls IsValidFormatFunc.
func (mock *FormatValidatorMock) IsValidFormat(format string) bool {
	if mock.IsValidFormatFunc == nil {
		panic("FormatValidatorMock.IsValidFormatFunc: method is nil but FormatValidator.IsValidFormat was just called")
	}
	callInfo := struct {
		Format string
	}{
		Format: format,
	}
	mock.lockIsValidFormat.Lock()
	mock.calls.IsValidFormat = append(mock.calls.IsValidFormat, callInfo)
	mock.lockIsValidFormat.Unlock()
	return mock.IsValidFormatFunc(format)
}

// IsValidFormatCalls gets all the calls that were made to IsValidFormat.
// Check the length with:
//
//	len(mockedFormatValidator.IsValidFormatCalls())
func (mock *FormatValidatorMock) IsValidFormatCalls() []struct {
	Format string
} {
	var calls []struct {
		Format string
	}
	mock.lockIsValidFormat.RLock()
	calls = mock.calls.IsValidFormat
	mock.lockIsValidFormat.RUnlock()
	return calls
}
