// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/git"
)

// GitServiceMock is a mock implementation of api.GitService.
//
//	func TestSomethingThatUsesGitService(t *testing.T) {
//
//		// make and configure a mocked api.GitService
//		mockedGitService := &GitServiceMock{
//			CommitFunc: func(req git.CommitRequest) error {
//				panic("mock out the Commit method")
//			},
//			DeleteFunc: func(key string, author git.Author) error {
//				panic("mock out the Delete method")
//			},
//			GetRevisionFunc: func(key string, rev string) ([]byte, string, error) {
//				panic("mock out the GetRevision method")
//			},
//			HistoryFunc: func(key string, limit int) ([]git.HistoryEntry, error) {
//				panic("mock out the History method")
//			},
//		}
//
//		// use mockedGitService in code that requires api.GitService
//		// and then make assertions.
//
//	}
type GitServiceMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func(req git.CommitRequest) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(key string, author git.Author) error

	// GetRevisionFunc mocks the GetRevision method.
	GetRevisionFunc func(key string, rev string) ([]byte, string, error)

	// HistoryFunc mocks the History method.
	HistoryFunc func(key string, limit int) ([]git.HistoryEntry, error)

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Req is the req argument value.
			Req git.CommitRequest
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Key is the key argument value.
			Key string
			// Author is the author argument value.
			Author git.Author
		}
		// GetRevision holds details about calls to the GetRevision method.
		GetRevision []struct {
			// Key is the key argument value.
			Key string
			// Rev is the rev argument value.
			Rev string
		}
		// History holds details about calls to the History method.
		History []struct {
			// Key is the key argument value.
			Key string
			// Limit is the limit argument value.
			Limit int
		}
	}
	lockCommit      sync.RWMutex
	lockDelete      sync.RWMutex
	lockGetRevision sync.RWMutex
	lockHistory     sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *GitServiceMock) Commit(req git.CommitRequest) error {
	if mock.CommitFunc == nil {
		panic("GitServiceMock.CommitFunc: method is nil but GitService.Commit was just called")
	}
	callInfo := struct {
		Req git.CommitRequest
	}{
		Req: req,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(req)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedGitService.CommitCalls())
func (mock *GitServiceMock) CommitCalls() []struct {
	Req git.CommitRequest
} {
	var calls []struct {
		Req git.CommitRequest
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *GitServiceMock) Delete(key string, author git.Author) error {
	if mock.DeleteFunc == nil {
		panic("GitServiceMock.DeleteFunc: method is nil but GitService.Delete was just called")
	}
	callInfo := struct {
		Key    string
		Author git.Author
	}{
		Key:    key,
		Author: author,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(key, author)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedGitService.DeleteCalls())
func (mock *GitServiceMock) DeleteCalls() []struct {
	Key    string
	Author git.Author
} {
	var calls []struct {
		Key    string
		Author git.Author
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetRevision calls GetRevisionFunc.
func (mock *GitServiceMock) GetRevision(key string, rev string) ([]byte, string, error) {
	if mock.GetRevisionFunc == nil {
		panic("GitServiceMock.GetRevisionFunc: method is nil but GitService.GetRevision was just called")
	}
	callInfo := struct {
		Key string
		Rev string
	}{
		Key: key,
		Rev: rev,
	}
	mock.lockGetRevision.Lock()
	mock.calls.GetRevision = append(mock.calls.GetRevision, callInfo)
	mock.lockGetRevision.Unlock()
	return mock.GetRevisionFunc(key, rev)
}

// GetRevisionCalls gets all the calls that were made to GetRevision.
// Check the length with:
//
//	len(mockedGitService.GetRevisionCalls())
func (mock *GitServiceMock) GetRevisionCalls() []struct {
	Key string
	Rev string
} {
	var calls []struct {
		Key string
		Rev string
	}
	mock.lockGetRevision.RLock()
	calls = mock.calls.GetRevision
	mock.lockGetRevision.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *GitServiceMock) History(key string, limit int) ([]git.HistoryEntry, error) {
	if mock.HistoryFunc == nil {
		panic("GitServiceMock.HistoryFunc: method is nil but GitService.History was just called")
	}
	callInfo := struct {
		Key   string
		Limit int
	}{
		Key:   key,
		Limit: limit,
	}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	return mock.HistoryFunc(key, limit)
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedGitService.HistoryCalls())
func (mock *GitServiceMock) HistoryCalls() []struct {
	Key   string
	Limit int
} {
	var calls []struct {
		Key   string
		Limit int
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}
