// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/store"
)

// KVStoreMock is a mock implementation of api.KVStore.
//
//	func TestSomethingThatUsesKVStore(t *testing.T) {
//
//		// make and configure a mocked api.KVStore
//		mockedKVStore := &KVStoreMock{
//			DeleteFunc: func(key string) error {
//				panic("mock out the Delete method")
//			},
//			GetFunc: func(key string) ([]byte, error) {
//				panic("mock out the Get method")
//			},
//			GetWithFormatFunc: func(key string) ([]byte, string, error) {
//				panic("mock out the GetWithFormat method")
//			},
//			ListFunc: func() ([]store.KeyInfo, error) {
//				panic("mock out the List method")
//			},
//			SetFunc: func(key string, value []byte, format string) error {
//				panic("mock out the Set method")
//			},
//		}
//
//		// use mockedKVStore in code that requires api.KVStore
//		// and then make assertions.
//
//	}
type KVStoreMock struct {
	// DeleteFunc mocks the Delete method.
	DeleteFunc func(key string) error

	// GetFunc mocks the Get method.
	GetFunc func(key string) ([]byte, error)

	// GetWithFormatFunc mocks the GetWithFormat method.
	GetWithFormatFunc func(key string) ([]byte, string, error)

	// ListFunc mocks the List method.
	ListFunc func() ([]store.KeyInfo, error)

	// SetFunc mocks the Set method.
	SetFunc func(key string, value []byte, format string) error

	// calls tracks calls to the methods.
	calls struct {
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Key is the key argument value.
			Key string
		}
		// GetWithFormat holds details about calls to the GetWithFormat method.
		GetWithFormat []struct {
			// Key is the key argument value.
			Key string
		}
		// List holds details about calls to the List method.
		List []struct {
		}
		// Set holds details about calls to the Set method.
		Set []struct {
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
			// Format is the format argument value.
			Format string
		}
	}
	lockDelete        sync.RWMutex
	lockGet           sync.RWMutex
	lockGetWithFormat sync.RWMutex
	lockList          sync.RWMutex
	lockSet           sync.RWMutex
}

// Delete calls DeleteFunc.
func (mock *KVStoreMock) Delete(key string) error {
	if mock.DeleteFunc == nil {
		panic("KVStoreMock.DeleteFunc: method is nil but KVStore.Delete was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(key)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedKVStore.DeleteCalls())
func (mock *KVStoreMock) DeleteCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *KVStoreMock) Get(key string) ([]byte, error) {
	if mock.GetFunc == nil {
		panic("KVStoreMock.GetFunc: method is nil but KVStore.Get was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedKVStore.GetCalls())
func (mock *KVStoreMock) GetCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetWithFormat calls GetWithFormatFunc.
func (mock *KVStoreMock) GetWithFormat(key string) ([]byte, string, error) {
	if mock.GetWithFormatFunc == nil {
		panic("KVStoreMock.GetWithFormatFunc: method is nil but KVStore.GetWithFormat was just called")
	}
	callInfo := struct {
		Key string
	}{
		Key: key,
	}
	mock.lockGetWithFormat.Lock()
	mock.calls.GetWithFormat = append(mock.calls.GetWithFormat, callInfo)
	mock.lockGetWithFormat.Unlock()
	return mock.GetWithFormatFunc(key)
}

// GetWithFormatCalls gets all the calls that were made to GetWithFormat.
// Check the length with:
//
//	len(mockedKVStore.GetWithFormatCalls())
func (mock *KVStoreMock) GetWithFormatCalls() []struct {
	Key string
} {
	var calls []struct {
		Key string
	}
	mock.lockGetWithFormat.RLock()
	calls = mock.calls.GetWithFormat
	mock.lockGetWithFormat.RUnlock()
	return calls
}

// List calls ListFunc.
func (mock *KVStoreMock) List() ([]store.KeyInfo, error) {
	if mock.ListFunc == nil {
		panic("KVStoreMock.ListFunc: method is nil but KVStore.List was just called")
	}
	callInfo := struct {
	}{}
	mock.lockList.Lock()
	mock.calls.List = append(mock.calls.List, callInfo)
	mock.lockList.Unlock()
	return mock.ListFunc()
}

// ListCalls gets all the calls that were made to List.
// Check the length with:
//
//	len(mockedKVStore.ListCalls())
func (mock *KVStoreMock) ListCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockList.RLock()
	calls = mock.calls.List
	mock.lockList.RUnlock()
	return calls
}

// Set calls SetFunc.
func (mock *KVStoreMock) Set(key string, value []byte, format string) error {
	if mock.SetFunc == nil {
		panic("KVStoreMock.SetFunc: method is nil but KVStore.Set was just called")
	}
	callInfo := struct {
		Key    string
		Value  []byte
		Format string
	}{
		Key:    key,
		Value:  value,
		Format: format,
	}
	mock.lockSet.Lock()
	mock.calls.Set = append(mock.calls.Set, callInfo)
	mock.lockSet.Unlock()
	return mock.SetFunc(key, value, format)
}

// SetCalls gets all the calls that were made to Set.
// Check the length with:
//
//	len(mockedKVStore.SetCalls())
func (mock *KVStoreMock) SetCalls() []struct {
	Key    string
	Value  []byte
	Format string
} {
	var calls []struct {
		Key    string
		Value  []byte
		Format string
	}
	mock.lockSet.RLock()
	calls = mock.calls.Set
	mock.lockSet.RUnlock()
	return calls
}
