// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"net/http"
	"sync"
)

// AuthProviderMock is a mock implementation of sse.AuthProvider.
//
//	func TestSomethingThatUsesAuthProvider(t *testing.T) {
//
//		// make and configure a mocked sse.AuthProvider
//		mockedAuthProvider := &AuthProviderMock{
//			EnabledFunc: func() bool {
//				panic("mock out the Enabled method")
//			},
//			FilterKeysForRequestFunc: func(r *http.Request, keys []string) []string {
//				panic("mock out the FilterKeysForRequest method")
//			},
//		}
//
//		// use mockedAuthProvider in code that requires sse.AuthProvider
//		// and then make assertions.
//
//	}
type AuthProviderMock struct {
	// EnabledFunc mocks the Enabled method.
	EnabledFunc func() bool

	// FilterKeysForRequestFunc mocks the FilterKeysForRequest method.
	FilterKeysForRequestFunc func(r *http.Request, keys []string) []string

	// calls tracks calls to the methods.
	calls struct {
		// Enabled holds details about calls to the Enabled method.
		Enabled []struct {
		}
		// FilterKeysForRequest holds details about calls to the FilterKeysForRequest method.
		FilterKeysForRequest []struct {
			// R is the r argument value.
			R *http.Request
			// Keys is the keys argument value.
			Keys []string
		}
	}
	lockEnabled              sync.RWMutex
	lockFilterKeysForRequest sync.RWMutex
}

// Enabled calls EnabledFunc.
func (mock *AuthProviderMock) Enabled() bool {
	if mock.EnabledFunc == nil {
		panic("AuthProviderMock.EnabledFunc: method is nil but AuthProvider.Enabled was just called")
	}
	callInfo := struct {
	}{}
	mock.lockEnabled.Lock()
	mock.calls.Enabled = append(mock.calls.Enabled, callInfo)
	mock.lockEnabled.Unlock()
	return mock.EnabledFunc()
}

// EnabledCalls gets all the calls that were made to Enabled.
// Check the length with:
//
//	len(mockedAuthProvider.EnabledCalls())
func (mock *AuthProviderMock) EnabledCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockEnabled.RLock()
	calls = mock.calls.Enabled
	mock.lockEnabled.RUnlock()
	return calls
}

// FilterKeysForRequest calls FilterKeysForRequestFunc.
func (mock *AuthProviderMock) FilterKeysForRequest(r *http.Request, keys []string) []string {
	if mock.FilterKeysForRequestFunc == nil {
		panic("AuthProviderMock.FilterKeysForRequestFunc: method is nil but AuthProvider.FilterKeysForRequest was just called")
	}
	callInfo := struct {
		R    *http.Request
		Keys []string
	}{
		R:    r,
		Keys: keys,
	}
	mock.lockFilterKeysForRequest.Lock()
	mock.calls.FilterKeysForRequest = append(mock.calls.FilterKeysForRequest, callInfo)
	mock.lockFilterKeysForRequest.Unlock()
	return mock.FilterKeysForRequestFunc(r, keys)
}

// FilterKeysForRequestCalls gets all the calls that were made to FilterKeysForRequest.
// Check the length with:
//
//	len(mockedAuthProvider.FilterKeysForRequestCalls())
func (mock *AuthProviderMock) FilterKeysForRequestCalls() []struct {
	R    *http.Request
	Keys []string
} {
	var calls []struct {
		R    *http.Request
		Keys []string
	}
	mock.lockFilterKeysForRequest.RLock()
	calls = mock.calls.FilterKeysForRequest
	mock.lockFilterKeysForRequest.RUnlock()
	return calls
}
