// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"sync"

	"github.com/umputun/stash/app/git"
)

// StorerMock is a mock implementation of git.Storer.
//
//	func TestSomethingThatUsesStorer(t *testing.T) {
//
//		// make and configure a mocked git.Storer
//		mockedStorer := &StorerMock{
//			CommitFunc: func(req git.CommitRequest) error {
//				panic("mock out the Commit method")
//			},
//			DeleteFunc: func(key string, author git.Author) error {
//				panic("mock out the Delete method")
//			},
//			GetRevisionFunc: func(key string, rev string) ([]byte, string, error) {
//				panic("mock out the GetRevision method")
//			},
//			HistoryFunc: func(key string, limit int) ([]git.HistoryEntry, error) {
//				panic("mock out the History method")
//			},
//			PullFunc: func() error {
//				panic("mock out the Pull method")
//			},
//			PushFunc: func() error {
//				panic("mock out the Push method")
//			},
//		}
//
//		// use mockedStorer in code that requires git.Storer
//		// and then make assertions.
//
//	}
type StorerMock struct {
	// CommitFunc mocks the Commit method.
	CommitFunc func(req git.CommitRequest) error

	// DeleteFunc mocks the Delete method.
	DeleteFunc func(key string, author git.Author) error

	// GetRevisionFunc mocks the GetRevision method.
	GetRevisionFunc func(key string, rev string) ([]byte, string, error)

	// HistoryFunc mocks the History method.
	HistoryFunc func(key string, limit int) ([]git.HistoryEntry, error)

	// PullFunc mocks the Pull method.
	PullFunc func() error

	// PushFunc mocks the Push method.
	PushFunc func() error

	// calls tracks calls to the methods.
	calls struct {
		// Commit holds details about calls to the Commit method.
		Commit []struct {
			// Req is the req argument value.
			Req git.CommitRequest
		}
		// Delete holds details about calls to the Delete method.
		Delete []struct {
			// Key is the key argument value.
			Key string
			// Author is the author argument value.
			Author git.Author
		}
		// GetRevision holds details about calls to the GetRevision method.
		GetRevision []struct {
			// Key is the key argument value.
			Key string
			// Rev is the rev argument value.
			Rev string
		}
		// History holds details about calls to the History method.
		History []struct {
			// Key is the key argument value.
			Key string
			// Limit is the limit argument value.
			Limit int
		}
		// Pull holds details about calls to the Pull method.
		Pull []struct {
		}
		// Push holds details about calls to the Push method.
		Push []struct {
		}
	}
	lockCommit      sync.RWMutex
	lockDelete      sync.RWMutex
	lockGetRevision sync.RWMutex
	lockHistory     sync.RWMutex
	lockPull        sync.RWMutex
	lockPush        sync.RWMutex
}

// Commit calls CommitFunc.
func (mock *StorerMock) Commit(req git.CommitRequest) error {
	if mock.CommitFunc == nil {
		panic("StorerMock.CommitFunc: method is nil but Storer.Commit was just called")
	}
	callInfo := struct {
		Req git.CommitRequest
	}{
		Req: req,
	}
	mock.lockCommit.Lock()
	mock.calls.Commit = append(mock.calls.Commit, callInfo)
	mock.lockCommit.Unlock()
	return mock.CommitFunc(req)
}

// CommitCalls gets all the calls that were made to Commit.
// Check the length with:
//
//	len(mockedStorer.CommitCalls())
func (mock *StorerMock) CommitCalls() []struct {
	Req git.CommitRequest
} {
	var calls []struct {
		Req git.CommitRequest
	}
	mock.lockCommit.RLock()
	calls = mock.calls.Commit
	mock.lockCommit.RUnlock()
	return calls
}

// Delete calls DeleteFunc.
func (mock *StorerMock) Delete(key string, author git.Author) error {
	if mock.DeleteFunc == nil {
		panic("StorerMock.DeleteFunc: method is nil but Storer.Delete was just called")
	}
	callInfo := struct {
		Key    string
		Author git.Author
	}{
		Key:    key,
		Author: author,
	}
	mock.lockDelete.Lock()
	mock.calls.Delete = append(mock.calls.Delete, callInfo)
	mock.lockDelete.Unlock()
	return mock.DeleteFunc(key, author)
}

// DeleteCalls gets all the calls that were made to Delete.
// Check the length with:
//
//	len(mockedStorer.DeleteCalls())
func (mock *StorerMock) DeleteCalls() []struct {
	Key    string
	Author git.Author
} {
	var calls []struct {
		Key    string
		Author git.Author
	}
	mock.lockDelete.RLock()
	calls = mock.calls.Delete
	mock.lockDelete.RUnlock()
	return calls
}

// GetRevision calls GetRevisionFunc.
func (mock *StorerMock) GetRevision(key string, rev string) ([]byte, string, error) {
	if mock.GetRevisionFunc == nil {
		panic("StorerMock.GetRevisionFunc: method is nil but Storer.GetRevision was just called")
	}
	callInfo := struct {
		Key string
		Rev string
	}{
		Key: key,
		Rev: rev,
	}
	mock.lockGetRevision.Lock()
	mock.calls.GetRevision = append(mock.calls.GetRevision, callInfo)
	mock.lockGetRevision.Unlock()
	return mock.GetRevisionFunc(key, rev)
}

// GetRevisionCalls gets all the calls that were made to GetRevision.
// Check the length with:
//
//	len(mockedStorer.GetRevisionCalls())
func (mock *StorerMock) GetRevisionCalls() []struct {
	Key string
	Rev string
} {
	var calls []struct {
		Key string
		Rev string
	}
	mock.lockGetRevision.RLock()
	calls = mock.calls.GetRevision
	mock.lockGetRevision.RUnlock()
	return calls
}

// History calls HistoryFunc.
func (mock *StorerMock) History(key string, limit int) ([]git.HistoryEntry, error) {
	if mock.HistoryFunc == nil {
		panic("StorerMock.HistoryFunc: method is nil but Storer.History was just called")
	}
	callInfo := struct {
		Key   string
		Limit int
	}{
		Key:   key,
		Limit: limit,
	}
	mock.lockHistory.Lock()
	mock.calls.History = append(mock.calls.History, callInfo)
	mock.lockHistory.Unlock()
	return mock.HistoryFunc(key, limit)
}

// HistoryCalls gets all the calls that were made to History.
// Check the length with:
//
//	len(mockedStorer.HistoryCalls())
func (mock *StorerMock) HistoryCalls() []struct {
	Key   string
	Limit int
} {
	var calls []struct {
		Key   string
		Limit int
	}
	mock.lockHistory.RLock()
	calls = mock.calls.History
	mock.lockHistory.RUnlock()
	return calls
}

// Pull calls PullFunc.
func (mock *StorerMock) Pull() error {
	if mock.PullFunc == nil {
		panic("StorerMock.PullFunc: method is nil but Storer.Pull was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPull.Lock()
	mock.calls.Pull = append(mock.calls.Pull, callInfo)
	mock.lockPull.Unlock()
	return mock.PullFunc()
}

// PullCalls gets all the calls that were made to Pull.
// Check the length with:
//
//	len(mockedStorer.PullCalls())
func (mock *StorerMock) PullCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPull.RLock()
	calls = mock.calls.Pull
	mock.lockPull.RUnlock()
	return calls
}

// Push calls PushFunc.
func (mock *StorerMock) Push() error {
	if mock.PushFunc == nil {
		panic("StorerMock.PushFunc: method is nil but Storer.Push was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPush.Lock()
	mock.calls.Push = append(mock.calls.Push, callInfo)
	mock.lockPush.Unlock()
	return mock.PushFunc()
}

// PushCalls gets all the calls that were made to Push.
// Check the length with:
//
//	len(mockedStorer.PushCalls())
func (mock *StorerMock) PushCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPush.RLock()
	calls = mock.calls.Push
	mock.lockPush.RUnlock()
	return calls
}
